### ISSUE TITLE
Create Lock-on feature

### ISSUE THREAD

**Issue by LongArmsLawrence** [dfpc-coe/CloudTAK#223]

**Comment by ingalls** [comment]
- This feature exists but is currently broken by the introduction of the "editing" mode in the CoTView side panel.
- Fix is likely "diffing" the properties but not the geometry to ensure that geometry

**Comment by LongArmsLawrence** [comment]
Ah shoot. Were you up late last night on this?

Ben Lawrence

COTAK Product Support Manager



P 970-665-0046 | C 970-966-4460

0375 County Road 352 #2065A, Building 2060
<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.google.com_maps_search_0375-2BCounty-2BRoad-2B352-2B-25232065A-2C-2BBuilding-2B2060-3Fentry-3Dgmail-26source-3Dg&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=Q5h8JluXGI61y1rhaI4K3yBoJCcg5QxvJpqBwQ5Qnww&m=vIiTF6rVXRX86QQUnyNa31UrJjYmJaOgAfnr8AGwT6uZ7ZczyO5GyfWqW_n5krXW&s=iHPFA92VDcGhR4ZXst9p0U4v7ALE2uffoFw8RzCK28I&e=>,
Rifle, CO 81650

***@***.*** | cofiretech.org
<https://urldefense.proofpoint.com/v2/url?u=http-3A__cofiretech.org_&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=ifU-9QWv-_QzxFkejS5OaNS3_pO5PrZN4A3ZzBKL2aI&m=LMDYkLQtYg8suhn2vaH8G5Q-9BzVqDvagUMAt0xZpewTfSl8K3MJxIsSFQoq2nPa&s=yDTpZWCoqV4a7yPB2GIa18mhLwV95qrXVqX3tiGdl7s&e=>
 | cotak.gov
<https://urldefense.proofpoint.com/v2/url?u=http-3A__cotak.gov_&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=ifU-9QWv-_QzxFkejS5OaNS3_pO5PrZN4A3ZzBKL2aI&m=LMDYkLQtYg8suhn2vaH8G5Q-9BzVqDvagUMAt0xZpewTfSl8K3MJxIsSFQoq2nPa&s=bhPNeGW2dc2ekJHYsbTUhNVnX1OiYmwzAiLWsxbMo24&e=>


Pursuant to Colorado's Open Records Act (CORA), all e-mails sent by or to
me on this state-owned e-mail account may be subject to public disclosure.
