### ISSUE TITLE
Switch orientation of back arrow to point to the right

### ISSUE THREAD

**Issue by LongArmsLawrence** [dfpc-coe/CloudTAK#232]
It would make more intuitive sense for the arrow that minimizes the menu to point back to the right instead of to the left
![back arrow](https://github.com/user-attachments/assets/15d19fc8-aba4-4bb3-9e00-d9c586eeb9cb)
.

**Comment by ingalls** [comment]
![image](https://github.com/user-attachments/assets/fcd1d337-45e1-4a13-bf1c-6f640cb09018)

If closing the menu will go to the Home Page we now show an X

If closing the menu will go to the menu list page we show a back button.
