### ISSUE TITLE
When a CoT is clicked on an error occurs

### ISSUE THREAD

**Issue by LongArmsLawrence** [dfpc-coe/CloudTAK#239]
When the pencil is highlighted in the radial menu, clicking to disable the pencil, the attached error(s) occur. Then, the CoT disappears from the screen and stays centered on the CoT's former location -- forcing a refresh.

![Click on CoT](https://github.com/user-attachments/assets/de8fe989-0138-47a4-af23-25518a7f5293)

**Comment by LongArmsLawrence** [comment]
This error also occurs on a different CoT
![Click on CoT2](https://github.com/user-attachments/assets/f97e98cf-a92b-4d6e-a9f4-77967db6c825)

**Comment by ingalls** [comment]
@LongArmsLawrence These should both now be resolved with v2.77.2 (deployed). 
- The first issue was with 3 coordinate positions on editing (3rd being elevation), we now truncate to 2 when editing
- Second issue is solved by implementing a acustom ID strategy in our editing library.

Please feel free to reopen or create a new issue if you continue to see this in the wild.
