### ISSUE TITLE
Streamline data imports (KML format)

### ISSUE THREAD

**Issue by LongArmsLawrence** [dfpc-coe/CloudTAK#246]
Create logic to seamlessly import KML features via the import function.

**Comment by ingalls** [comment]
This has been partially completed

- Data Imports now take place only in the CloudTAK Map view (The profile page outside of the map view no longer exists)
- Lambda => Batch w/ logs is now seamless to the user
- The Import page now shows lambda => Batch status in a unified way

TODO:
- https://github.com/dfpc-coe/CloudTAK/issues/292
- https://github.com/dfpc-coe/CloudTAK/issues/290

Closing this ticket in favour of more targeted sub-tickets. Thanks for the report @LongArmsLawrence !
